services:
  - docker:dind

stages:
  - build

docker_build:
  stage: build
  image: docker:latest
  script:
    - docker build -t private.parrot.run/documentation:latest .
    - echo $DOCKER_REGISTRY_PASSWORD | docker login -u $DOCKER_REGISTRY_USER --password-stdin
    - docker push private.parrot.run/documentationg:latest