[book]
authors = ["Parrot Team"]
language = "en"
multilingual = true
src = "src"
title = "Parrot Documentation"
description = "New documentation for Parrot OS"

[build]
build-dir = "build"
create-missing = false

[output.html]
theme = "parrot-theme" # tweak this theme here: /parrot-theme/css/variables.css
default-theme = "parrot"
preferred-dark-theme = "parrot"
mathjax-support = false
additional-css = ["static/custom.css"]
additional-js = ["static/custom.js"]
no-section-label = true
# git-repository-url = "nest.parrotsec.org"

[output.html.print]
enable = false

[output.html.search]
enable = true
limit-results = 15
teaser-word-count = 15
expand = true
heading-split-level = 3

[output.html.fold]
enable = true
level = 0

[language.en]
name = "Parrot OS Documentation"
title = "Parrot Documentation"
description = "Documentation for Parrot OS"

[language.es]
name = "Parrot OS Spanish Documentation"
title = "Parrot Documentación"
description = "Documentación para ParrotOS"

[language.fr]
name = "Parrot OS French Documentation"
title = "Documentation Parrot"
description = "Documentation pour ParrotOS"