site_name: Parrot Documentation
site_url: https://docs.parrotsec.org

theme:
    name: cyborg
#    highlightjs: true
#    hljs_languages:
#        - yaml
#        - rust
#        - c
#        - python
#        - bash
#        - cpp
#        - perl


nav:
    - Parrot Website: https://www.parrotsec.org
    - Introduction:
        - intro/what-is-parrot.md
        - intro/should-i-use-parrot.md
        - intro/what-is-debian.md
        - intro/what-is-linux.md
    - Getting Started:
        - getting-started/system-requirements.md
        - getting-started/download.md
        - getting-started/create-boot-device.md
        - getting-started/what-is-live-mode.md
        - getting-started/how-to-boot.md
    - Installation:
        - installation/install-parrot.md
        - installation/before-installing.md    
    - Project:
        - mirror-list.md
        - community.md
        - team.md
        - partners.md
        - weathermap.md
        - warrant-canary.md
        - donate.md
    - F.A.Q.: faq.md
