site_name: Parrot Documentation
site_url: https://docs.parrotsec.org

theme:
    name: cyborg
#    highlightjs: true
#    hljs_languages:
#        - yaml
#        - rust
#        - c
#        - python
#        - bash
#        - cpp
#        - perl


nav:
    - Parrot Website: https://www.parrotsec.org
    - Introduction:
        - What is Parrot: intro/what-is-parrot.md
        - What is Debian: intro/what-is-debian.md
        - What is Linux: intro/what-is-linux.md
    - Getting Started:
        - Download Parrot: getting-started/download.md
        - Create a boot device: getting-started/create-boot-device.md
        - How to boot the system: getting-started/how-to-boot.md
        - Parrot on Docker: getting-started/parrot-on-docker.md
    - Project:
        - Infrastructure:
            - APT Mirror list: mirror-list.md
            - Make your own mirror: https://www.parrotsec.org/docs/mirror-list/#make-your-own-mirror
            - Infrastructure Weathermap: weathermap.md
            - Warrant Canary: warrant-canary.md
        - community.md
        - team.md
        - partners.md
        - donate.md
    - F.A.Q.: faq.md
