
site_name: Parrot Documentation
site_url: https://docs.parrot.sh
site_author: Parrot Team
copyright: <p><br/>
            <span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">Parrot Documentation</span> is written by the <a
                xmlns:cc="http://creativecommons.org/ns#" href="https://docs.parrot.sh/team/" property="cc:attributionName"
                rel="cc:attributionURL">Parrot Team</a> <br> Copyright © Lorenzo "Palinuro" Faletra 2019 some rights reserved.  <br> Licensed under a <a rel="license"
                href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons BY-SA 4.0 International License</a>.
            <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License"
                    style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/80x15.png" /></a></p>                

theme:
    name: cyborg


nav:
    - Parrot Website: https://www.parrot.sh
    - Introduction:
        - What is Parrot: intro/what-is-parrot.md
        - What is Debian: intro/what-is-debian.md
        - What is Linux: intro/what-is-linux.md
    - User Guide:
        - Getting Started: getting-started/start.md
        - Using Parrot: info/start.md    
        - Troubleshooting: trbl/start.md
    - Library: 
        - ParrotOS: library/start.md
        - Knowledge Nest: library/knowledge-start.md  
    - The Project:
        - Infrastructure:
            - APT Mirror list: mirror-list.md
            - Make your own mirror: mirror-list/#make-your-own-mirror
            - Infrastructure Weathermap: weathermap.md
        - Community: 
            - News: https://blog.parrot.sh/
            - Future Plans: roadmap.md
            - Social Media: community.md
            - The Team: team.md
            - Partners: partners.md
            - Donate: donate.md
            - Nest: https://nest.parrotsec.org/explore/groups
        - Legal: legal/legal-start.md
        - Warrant Canary: legal/warrant-canary.md
    - F.A.Q.: faq.md

