site_name: Parrot Documentation
site_url: https://docs.parrotsec.org

theme:
    name: cyborg
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
        - c
        - python
        - bash
        - cpp
        - perl

nav:
    - Parrot Website: https://www.parrotsec.org
    - Introduction:
        - intro/what-is-parrot.md
        - intro/should-i-use-parrot.md
    - Getting Started:
        - getting-started/01.download.md
        - getting-started/02.create-boot-device.md
        - getting-started/03.how-to-boot.md
        - getting-started/04.use-parrot.md
        - getting-started/05.install-parrot.md
    - Parrot Project:
        - mirror-list.md
        - community.md
        - team.md
        #- partners.md
